# Generated by Django 4.2.4 on 2023-09-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('2D', '2D Animation'), ('3D', '3D Animation')], max_length=2)),
                ('character', models.CharField(max_length=100)),
                ('dir_head', models.CharField(max_length=100)),
                ('emotion', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=10)),
                ('dir_eye', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('foreground', models.CharField(max_length=100)),
            ],
        ),
    ]
